# Colors (Gruvbox Material Hard Dark)

[colors.primary]
background = '#141617'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
blue    = '#83a598'
yellow  = '#d8a657'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
