#!/bin/sh

# Increment, decrement, or mute the volume and send a notification
# of the current volume level.

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5
	;;
down)
	pamixer -u
	pamixer -d 5 
	;;
mute)
	pamixer -t
esac
